feat: add logic for ordering output
lorentzforces/TempBot pull request #1
Opened 2017-11-13 20:03 UTC by rjdabbar

2017-11-13 20:04 UTC, rjdabbar commented
@lorentzforces  dunno if this is logically correct, ive not done anything in his language before since like hs.

2017-11-13 23:38 UTC, lorentzforces requested changes

2017-11-13 23:38 UTC, lorentzforces commented on src/fyi/lorentz/tempBot/service/TemperatureProcessor.java
>          DecimalFormat format = new DecimalFormat("###,###,###,###.###");
This needs to be declared in the scope it's used - should be moved to the handleStringFormatting method.

2017-11-13 23:38 UTC, lorentzforces commented on src/fyi/lorentz/tempBot/service/TemperatureProcessor.java
> +        String firstTemp = getTemperatureOrder(text);
Here we're checking for the presence of the unit character in the entire message text, which is likely to grab something else that happens to have an F or C in it. This should probably be called on a per-temperature basis. 

Debating to myself whether it's better to track indexes here in a separate array, or to throw a "convertedFrom" field on Temperature that denotes what the original unit was.

2017-12-03 01:48 UTC, lorentzforces commented
This issue has been resolved by PR #4.
Closing this PR.

2017-12-03 01:48 UTC, closed without merging